version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  mynginx:
    build: .
    image: mynginx
    container_name: mynginx
    ports:
      - "81:80"